@url=http://localhost:8888/api
@jsonContent = Content-Type: application/json

### 所有用户
get {{url}}/users

### 注册
post {{url}}/register
{{jsonContent}}

{
    "username": "user2",
    "password": "123456"
}

### 登录
post {{url}}/login
{{jsonContent}}

{
    "username": "user2",
    "password": "123456"
}
### 个人信息
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOWZhMmU5MDQyOWEzMjkzZmFlZDgxMCIsImlhdCI6MTYwNDI5ODgwMH0.3oKP9jX1DX4ARAVI8WCgCSKAG1t4Dz0IwOdhpBWvowI

